version: '1.0'

stages:
- test

steps:

  SetupEnvironment:
    title: Setup environment
    image: &testbed chartmuseum/testbed:latest
    commands:
    - make clean
    - cf_export GOCACHE=/codefresh/volume/mod
    - make bootstrap

  RunUnitTests:
    stage: test
    title: Run unit tests
    image: *testbed
    commands:
    - make test
