version: '1.0'

stages:
- test

steps:

  SetupEnvironment:
    title: Setup environment
    image: &testbed chartmuseum/testbed:latest
    commands:
    - make clean

  RunUnitTests:
    stage: test
    title: Run unit tests
    image: *testbed
    commands:
    - make test
